spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: t1542983487
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
